{% set name = "pybcj" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b682ed08caabfb7c042d4be083e28ddc692afb1deff5567111f8855071b75c3

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=42.0
    - setuptools-scm >=3.5.0
  run:
    - importlib-metadata  # [py<38]
    - python

test:
  imports:
    - bcj
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miurahr/pybcj
  summary: bcj filter library
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
