{% set name = "pybcj" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72d64574069ffb0a800020668376b7ebd7adea159adbf4d35f8effc62f0daa67

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=42.0
    - setuptools-scm >=3.5.0
  run:
    - importlib-metadata  # [py<38]
    - python

test:
  imports:
    - bcj
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miurahr/pybcj
  summary: bcj filter library
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
